### ISSUE TITLE
[App Mobile SciELO] Servidor indisponível

### ISSUE THREAD

**Issue by javani** [Infobase/pulsemob_backoffice#1]
Quando tento acessar a plataforma apresenta o erro de servidor temporariamente indisponível.
![image](https://cloud.githubusercontent.com/assets/912953/12674512/a8d77d3a-c66a-11e5-84e0-b47595b2bc9e.png)

**Comment by leobueno** [comment]
Javani, 

  O servidor foi reiniciado para manutenção no nobreak, em alguns minutos estará disponível novamente. Aviso assim que retornar o serviço ao ar.

Att

**Comment by fabiobatalha** [comment]
@leobueno 

Estou recomendando a equipe a abrir os tickets em nosso repositório.

Este ticket deve ser encerrado aqui e continuar em: https://github.com/scieloorg/pulsemob_backoffice/issues

Os tickets relacionados ao app e ao backoffice seram abertos em nossos reps.

Recomendo acompanhá-los.

**Comment by leobueno** [comment]
Ok Fabio

Leonardo Bueno
www.infobase.com.br
Tel: (27) 3207-9266
Cel: (27) 99257-0872

2016-01-29 9:49 GMT-02:00 Fabio Batalha notifications@github.com:

**Comment by javani** [comment]
@leobueno já está funcionando.
